BHTecEventos/Models/Eventos.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHTecEventos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eventos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Eventos()
        {
            this.Pessoas_Eventos = new HashSet<Pessoas_Eventos>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public System.DateTime DataCriado { get; set; }
        public System.DateTime DataLimite { get; set; }
        public int LimitePessoas { get; set; }
        public string Organizador { get; set; }
        public int UsuarioResponsavel { get; set; }
        public bool Ativo { get; set; }
        public System.DateTime DataAcontecimento { get; set; }
        public int CargaHoraria { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pessoas_Eventos> Pessoas_Eventos { get; set; }
    }
}

BHTecEventos/Controllers/EventoController.cs
using BHTecEventos.AuxCode;
using BHTecEventos.Controllers;
using BHTecEventos.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebMatrix.WebData;

namespace BHTecEventos.Controllers
{
    public class EventoController : Controller
    {
        private EntitiesBHTecEventos db = new EntitiesBHTecEventos();

        //
        // GET: /Evento/

        public ActionResult Index()
        {
            return View(new EventoCPFModel());

        }

        [HttpGet]
        public ActionResult CadastrarEvento()
        {
            return View();
        }


        //POST: /Evento/CadastrarEvento
        //[CustomAuthorize(new int[] { 3 })]
        [HttpPost]
        public ActionResult CadastrarEvento(CadastroEventoModel m)
        {
            TempData["atencao"] = "";
            TempData["mensagem"] = "";

            if (ModelState.IsValid)
            {
                this.AdicionarEvento(m);
                TempData["mensagem"] = "Evento criado com sucesso.";
                
            }
            else
            {
                var message = string.Join(" | ", ModelState.Values
                            .SelectMany(v => v.Errors)
                            .Select(e => e.ErrorMessage));
                TempData["atencao"] = message;
                return View();
            }
            var model = db.Eventos.ToList();
            return View("IndexEvento", model);
        }

        public void AdicionarEvento(CadastroEventoModel cs)
        {

            var idUser = db.Usuarios.FirstOrDefault(a => a.Nome == User.Identity.Name);
            db.Eventos.Add(new Eventos
            {
                Id = cs.Id,
                Nome = cs.Nome,
                DataCriado = DateTime.Now,
                DataLimite = cs.DataLimite,
                DataAcontecimento = cs.DataAcontecimento,
                UsuarioResponsavel = Convert.ToInt32(idUser.Codigo),
                LimitePessoas = cs.LimitePessoas,
                CargaHoraria = cs.CargaHoraria,
                Organizador = cs.Organizador,
                Ativo = cs.Ativo

            });
            db.SaveChanges();

        }


        //[CustomAuthorize(new int[] { 3 })]
        public ActionResult IndexEvento()
        {

            var model = db.Eventos.ToList();
            return View(model);
        }

        //[CustomAuthorize(new int[] { 3 })]
        public ActionResult EditEvento(int id = 0)
        {
            var model = db.Eventos.Find(id);
            EventoModel SM = new EventoModel();
            SM.Id = model.Id;
            SM.Nome = model.Nome;
            SM.DataCriado = model.DataCriado;
            SM.DataLimite = model.DataLimite.Date.ToString();
            SM.DataAcontecimento = model.DataAcontecimento.Date.ToString();
            SM.LimitePessoas = model.LimitePessoas;
            SM.CargaHoraria = model.CargaHoraria;
            SM.Organizador = model.Organizador;
            SM.UsuarioResponsavel = model.UsuarioResponsavel;
            SM.NomeUsuario = model.Usuarios.Nome;
            SM.Ativo = model.Ativo;


            return View(SM);
        }

        //[CustomAuthorize(new int[] { 3 })]
        [HttpPost]
        public ActionResult EditEvento(Eventos model)
        {
            var idUser = db.Usuarios.FirstOrDefault(a => a.Nome == User.Identity.Name);

            TempData["mensagem"] = "";

            if (ModelState.IsValid)
            {
                var SM = db.Eventos.Find(model.Id);

                SM.Nome = model.Nome;
                SM.DataLimite = model.DataLimite;
                SM.DataAcontecimento = model.DataAcontecimento;
                SM.LimitePessoas = model.LimitePessoas;
                SM.CargaHoraria = model.CargaHoraria;
                SM.Organizador = model.Organizador;
                SM.UsuarioResponsavel = Convert.ToInt32(idUser.Codigo);
                SM.Ativo = model.Ativo;

                db.SaveChanges();
                TempData["mensagem"] = "Evento alterado com sucesso";
                return RedirectToAction("IndexEvento");
            }
            else
            {
                return View();
            }


        }

        public ActionResult DeleteEvento(int id = 0)
        {
            TempData["mensagem"] = "";
            var Evento = db.Eventos.Find(id);
            db.Eventos.Remove(Evento);
            db.SaveChanges();
            TempData["mensagem"] = "Seminário excluído com sucesso.";
            return RedirectToAction("IndexEvento");
        }



        public ActionResult BuscaCadastrados()
        {
            return View("~/Views/Evento/BuscaCadastrados.cshtml");
        }

        public ActionResult BuscaCadastroPessoa(EventoCPFModel Candidato)
        {

            TempData["mensagem"] = "";
            TempData["atencao"] = "";
            if (ModelState.IsValid)
            {
                //Verificar se é o administrador do sistema e redirecionar para tela de login
                //var Usu = db.Usuarios.FirstOrDefault(c => c.CPF == Candidato.CPF);
                //if (Usu != null)
                //{
                //    return View("~/Views/Admin/Login.cshtml");
                //}
                PessoaModel P = new PessoaModel();
                var Pessoa = db.Pessoas.FirstOrDefault(u => u.CPF == Candidato.CPF);
                if (Pessoa != null)
                {
                    return View("AtualizarPessoas", P.BuscarPessoa(Pessoa));
                }
                else
                {
                    return View("CadastrarPessoas");
                }
            }
            else
            {
                return View("Index");
            }
        }


        public ActionResult RegistraCandidatoAoEvento(String CPF, int Evento)
        {
            string Erro = "";
            TempData["mensagem"] = "";
            TempData["atencao"] = "";
            if (ModelState.IsValid)
            {

                var EstorouLimite = db.Eventos.Find(Evento);
                if (db.Pessoas_Eventos.Where(i => i.IdEvento == Evento).Count() >= EstorouLimite.LimitePessoas)
                {
                    TempData["atencao"] = "Não há mais vagas disponíveis para este evento. Obrigado";
                    return View("~/Views/Evento/MensagemSucessoPessoaEvento.cshtml");
                }

                var DataLimite = db.Eventos.Find(Evento).DataLimite;
                if (System.DateTime.Now > DataLimite)
                {
                    TempData["atencao"] = "O prazo para inscrição terminou no dia " + DataLimite.ToString("dd/MM/yyyy") + ". Obrigado";
                    return View("~/Views/Evento/MensagemSucessoPessoaEvento.cshtml");
                }
                var Pessoa = db.Pessoas.FirstOrDefault(n => n.CPF == CPF);

                if (VerificaSePessoaEstaNoEvento(Pessoa.Id, Convert.ToInt32(Evento)))
                {
                    TempData["mensagem"] = "Você já está cadastrado para o evento solicitado. Obrigado";
                    return View("~/Views/Evento/MensagemSucessoPessoaEvento.cshtml");
                }

                if (Pessoa != null)
                {
                    try
                    {
                        Pessoas_Eventos Gravar = new Pessoas_Eventos();
                        Gravar.IdPessoa = Pessoa.Id;
                        Gravar.IdEvento = Evento;
                        Gravar.DataInscricao = System.DateTime.Now;
                        db.Pessoas_Eventos.Add(Gravar);
                        db.SaveChanges();
                    }
                    catch (DbEntityValidationException e)
                    {
                        foreach (var eve in e.EntityValidationErrors)
                        {
                            //Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:", eve.Entry.Entity.GetType().Name, eve.Entry.State);
                            //Erro += "Entity of type \"{0}\" in state \"{1}\" has the following validation errors:" + eve.Entry.Entity.GetType().Name + eve.Entry.State;
                            foreach (var ve in eve.ValidationErrors)
                            {
                                //Console.WriteLine("- Property: \"{0}\", Error: \"{1}\"",ve.PropertyName, ve.ErrorMessage);
                                //Erro += "- Property: \"{0}\", Error: \"{1}\"" + ve.PropertyName + ve.ErrorMessage;
                                Erro += ve.ErrorMessage + "\n";
                            }
                        }
                        TempData["atencao"] = Erro;
                        return View("~/Views/Evento/CadastrarPessoaNoEvento.cshtml");
                    }
                }


            }
            TempData["mensagem"] = "Cadastro Realizado com sucesso. Obrigado.";
            return View("~/Views/Evento/MensagemSucessoPessoaEvento.cshtml");
        }

        private bool VerificaSePessoaEstaNoEvento(int Pessoa, int Evet)
        {
            var Evento = db.Pessoas_Eventos.FirstOrDefault(n => n.IdPessoa == Pessoa && n.IdEvento == Evet);
            if (Evento != null) return true;
            else { return false; }
        }

        public ActionResult Busca(String Nome, String Evento, String DataInicio, String DataFim)
        {
            //AJAX
            var query = db.ListaPessoasDoEvento.AsQueryable();
            if (ModelState.IsValid)
            {
                if (!String.IsNullOrEmpty(Nome))
                {
                    //var resultado = db.ListaPessoasDoEvento.Where(u => u.Nome.Contains(Nome)).OrderBy(u => u.Nome).ToList();
                    //return PartialView("~/Views/Evento/ListaPessoasCadastradas.cshtml", resultado);
                    query = query.Where(u => u.Nome.Contains(Nome)).OrderBy(u => u.Nome);

BHTecEventos/Controllers/PessoaController.cs
using BHTecEventos.Controllers;
using BHTecEventos.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace BHTecEventos.Controllers
{
    public class PessoaController : Controller
    {
        //
        // GET: /Pessoa/

        private EntitiesBHTecEventos db = new EntitiesBHTecEventos();

        //
        // GET: /Evento/

        public ActionResult Index()
        {
            return View(new EventoCPFModel());
        }

        public ActionResult CadastrarPessoas()
        {
            TempData["mensagem"] = "";
            TempData["atencao"] = "";
            return View("~/Views/Evento/CadastrarPessoas.cshtml");
        }

        [HttpPost]
        public ActionResult CadastrarPessoas(PessoaModel Pessoa)
        {
            string Erro = "";
            TempData["mensagem"] = "";
            TempData["atencao"] = "";
            if (ModelState.IsValid)
            {
                Erro = Pessoa.CadastrarPessoa(Pessoa);
                if (Erro == "") //Sucesso na gravação
                {
                    TempData["mensagem"] = "Cadastro Realizado com sucesso. Para concluir escolha o evento que deseja Participar";
                    Pessoa = new PessoaModel().BuscarPessoa(db.Pessoas.FirstOrDefault(c => c.CPF == Pessoa.CPF));
                    return View("~/Views/Evento/CadastrarPessoaNoEvento.cshtml", Pessoa);
                }
                else
                {
                    TempData["atencao"] = Erro;
                    return View("~/Views/Evento/CadastrarPessoas.cshtml");
                }
            }
            return View("~/Views/Evento/CadastrarPessoas.cshtml");
        }

        [HttpPost]
        public ActionResult AtualizarPessoas(PessoaModel Pessoa)
        {
            string Erro = "";
            TempData["mensagem"] = "";
            TempData["atencao"] = "";
            if (ModelState.IsValid)
            {
                Erro = Pessoa.AtualizarPessoa(Pessoa);
                if (Erro == "") //Sucesso na gravação
                {
                    TempData["mensagem"] = "Cadastro Realizado com sucesso. Para concluir escolha o evento que deseja Participar";
                    Pessoa = new PessoaModel().BuscarPessoa(db.Pessoas.FirstOrDefault(c => c.CPF == Pessoa.CPF));
                    return View("~/Views/Evento/CadastrarPessoaNoEvento.cshtml", Pessoa);
                }
                else
                {
                    TempData["atencao"] = Erro;
                    return View("~/Views/Evento/AtualizarPessoas.cshtml");
                }
            }
            return View("~/Views/Evento/AtualizarPessoas.cshtml");

        }

    }
}

BHTecEventos/Views/Evento/BuscaCadastrados.cshtml
@model SelectList
@using BHTecEventos.AuxCode
@{
    ViewBag.Title = "Index";
    ViewBag.T = "Index";
    Layout = "~/Views/Shared/_EventoLayout.cshtml";

    var db = new BHTecEventos.Models.EntitiesBHTecEventos();
    var ModelListas = new BHTecEventos.Models.PessoaModel();
    ModelListas.ListaEventos = new SelectList(db.Eventos.Where(a => a.Ativo == true).OrderBy(n => n.Nome), "Id", "Nome");
}

<h2>Busca Pessoas Cadastradas</h2>
@Html.ActionLink("Cadastrar Pessoa", "CadastrarPessoas","Pessoa",null,null)
<hr />
@using (Ajax.BeginForm("Busca", "Evento", new AjaxOptions { HttpMethod = "GET", InsertionMode = InsertionMode.Replace, LoadingElementId = "ajax-loader", UpdateTargetId = "result" }))
{
    <div class="form-group">
        <div class="col-md-5">
            @Html.Label("Nome:")
            @Html.TextBox("Nome", null, new { @class = "form-control", @placeholder = "Nome" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-5">
            @Html.Label("Evento:")
            @Html.DropDownList("Evento", ModelListas.ListaEventos, "-- Selecione o Seminário --", new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-2">
            @Html.Label("Data Inicio:")
            @Html.TextBox("DataInicio", null, new { @class = "form-control pt1", @type = "date", @placeholder = "Data Inicio" })
        </div>
        <div class="col-md-2">
            @Html.Label("Data Final:")
            @*@Html.TextBox("DataFim", DateTime.Today.Year + "-" + DateTime.Today.Month.ToString("#00") + "-" + DateTime.Today.Day.ToString("#00"), new { @class = "form-control pt2", @type = "date", @placeholder = "Data Fim" })*@
            @Html.TextBox("DataFim", DateTime.Today.ToString("yyyy-MM-dd"), new { @class = "form-control pt2", @type = "date", @placeholder = "Data Fim" })
        </div>
        <div class="col-md-2">
            <button type="submit" class="btn btn-primary" style="margin-top: 25px; clear: both">
                Buscar   <i class="fa fa-search"></i>
            </button>
            <img id="ajax-loader" src="~/Images/ajax-loader.gif" style=" display:none; margin-top: 1%" />
        </div>
    </div>
    @*<div class="form-group">
        <div class="col-md-2">
            <button type="submit" class="btn btn-primary" style="margin-top: 15px; clear: both">
                Buscar   <i class="fa fa-search"></i>
            </button>
            <img id="ajax-loader" src="~/Images/ajax-loader.gif" style=" display:none; margin-top: 1%" />
        </div>*@
        @*<div class="col-md-2">
            @Html.ActionLink("Cadastrar Pessoa", "CadastraPessoa", "Pessoa", new { @class = "btn btn-primary", @style = "margin-top: 15px; clear: both" })
        </div>
    </div>*@
}

<div id="result"></div>

BHTecEventos/Views/Evento/CadastrarEvento.cshtml
@model BHTecEventos.Models.CadastroEventoModel
@{
    ViewBag.Title = "CadastroEvento";
    Layout = "~/Views/Shared/_EventoLayout.cshtml";
    List<SelectListItem> ListaStatus = new List<SelectListItem>();
    ListaStatus.Add(new SelectListItem { Value = true.ToString(), Text = "Aberto" });
    ListaStatus.Add(new SelectListItem { Value = false.ToString(), Text = "Fechado" });

    var db = new BHTecEventos.Models.EntitiesBHTecEventos();
    var ModelListas = new BHTecEventos.Models.CadastroEventoModel();
    ModelListas.ListaUsuarios = new SelectList(db.Usuarios.OrderBy(n => n.Nome), "Codigo", "Nome");

}

<script>
    jQuery(function ($) {
        $("#DataLimite").mask("99/99/9999");
        $("#DataAcontecimento").mask("99/99/9999");
    });
</script>

<h2>Cadastrar Eventos</h2>
<small style="margin-left: 2px; color: lightblue gray; font-size: 15px">Adicione um novo Evento</small>
<hr />
@using (Html.BeginForm("CadastrarEvento", "Evento", FormMethod.Post))
{
    @Html.ValidationSummary(true);

    <div class="form-group">       
        <div class="col-lg-8">
            @Html.Label("Nome:")
            @Html.TextBoxFor(model => model.Nome, new { @class = "form-control pt1", @placeholder = "Nome", @required = true })
            @Html.ValidationMessageFor(model => model.Nome, null, new { @style = "color: #f00" })
        </div>
    </div>

    <div class="form-group">       
        <div class="col-lg-4">
            @Html.Label("Data Limite:")
            @Html.TextBoxFor( model => model.DataLimite, new { @class = "form-control pt1", @placeholder = "Data Limite", @required = true })
            @Html.ValidationMessageFor(model => model.DataLimite, null, new { @style = "color: #f00" })
        </div>

        <div class="col-lg-4">
            @Html.Label("Data do Evento:")
            @Html.TextBoxFor(model => model.DataAcontecimento, new { @class = "form-control pt1", @placeholder = "Data do Seminário", @required = true })
            @Html.ValidationMessageFor(model => model.DataAcontecimento, null, new { @style = "color:#f00" })
        </div>

    </div>

   

    <div class="form-group">        
        <div class="col-lg-4">
            @Html.Label("Limite de Pessoas:")
            @Html.TextBoxFor(model => model.LimitePessoas, new { @class = "form-control pt1", @placeholder = "Limite de Pessoas", @required = true })
            @Html.ValidationMessageFor(model => model.LimitePessoas, null, new { @style = "color: #f00" })
        </div>

        <div class="col-lg-4">
            @Html.Label("Carga Horária:")
            @Html.TextBoxFor(model => model.CargaHoraria, new { @class = "form-control pt1", @placeholder = "Carga Horária (Em Horas)", @required = true })
            @Html.ValidationMessageFor(model => model.CargaHoraria, null, new { @style = "color: #f00" })
        </div>

        <div class="col-md-4">
            @Html.Label("Status do Evento:")
            @Html.DropDownListFor(model => model.Ativo, ListaStatus, "-- Selecione o Status --", new { @class = "form-control pt1", @required = true })
            @Html.ValidationMessageFor(model => model.Ativo, null, new { @style = "color: #f00" })
        </div>
    </div>

    <div class="form-group">       
        <div class="col-lg-8">
            @Html.Label("Palestrante:")
            @Html.TextBoxFor(model => model.Organizador, new { @class = "form-control pt1", @placeholder = "Palestrante", @required = true })
            @Html.ValidationMessageFor(model => model.Organizador, null, new { @style = "color: #f00" })
        </div>
    </div>

    

    

    <div class="form-group">
        <div class="col-md-2">
            <input type="submit" value="Cadastrar" class="btn btn-primary" style="margin-top: 15px; clear: both">
        </div>
    </div>
    
   
}

BHTecEventos/Views/Evento/CadastrarPessoaNoEvento.cshtml
@model BHTecEventos.Models.PessoaModel

@{
    ViewBag.Title = "Index";
    ViewBag.T = "Index";
    Layout = "~/Views/Shared/_EventoLayout.cshtml";

    var db = new BHTecEventos.Models.EntitiesBHTecEventos();
    var ModelListas = new BHTecEventos.Models.PessoaModel();
    ModelListas.ListaEventos = new SelectList(db.Eventos.Where(a => a.Ativo == true && a.DataAcontecimento > System.DateTime.Now).OrderBy(n => n.Nome), "Id", "Nome");

    var ListEventos = db.Eventos.Where(a => a.Ativo == true && a.DataAcontecimento > System.DateTime.Now).OrderBy(n => n.Nome);
}


<div style="text-align:center; align-items:center">
    @*<img src="~/Images/logo_bhtec.jpg" width="200" />*@
    @if (TempData["mensagem"] != "")
    {
        <div class="alert alert-info">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            @TempData["mensagem"]
        </div>
    }

    @if (TempData["atencao"]!="")
    {
        <div class="alert alert-warning">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            @TempData["atencao"]
        </div>
    }
</div>
@using (Html.BeginForm("RegistraCandidatoAoEvento", "Evento", FormMethod.Post))
{
    @Html.ValidationSummary(true, null, new { @style = "color: #f00" })

    <div class="form-group">
        <div class="col-md-5">
            <h4>Olá @Html.Display("Nome")</h4>
            <p>Escolha o evento que deseja participar e clique em 'Inscrever'</p>
        </div>
    </div>

    if (ListEventos.Count() == 0)
    {
        <div class="alert alert-info">
            <h4>Não existem Cursos disponíveis no momento.</h4>
        </div>
    }
    else
    {
        <div class="form-group">
            <div class="col-md-12">
                @*@Html.LabelFor(model => model.Evento)
                    @Html.DropDownList("Evento", ModelListas.ListaEventos, "-- Selecione o Evento --", new { @class = "form-control" })*@
                <div class="table-responsive">
                    <table class="table table-striped" style="background-color:#fff; margin-top:1%">
                        <tr>
                            <th width="50%">Evento</th>
                            <th>Data</th>
                            <th>Carga Horária</th>
                            <th style="width:3%">Presença</th>
                        </tr>


                        @foreach (var item in ListEventos)
                        {
                            <tr>
                                <td>@item.Nome</td>                                
                                <td>@item.DataAcontecimento.ToString("dd/MM/yyyy")</td>
                                <td> @item.CargaHoraria</td>
                                @{
                            var Evento = db.Pessoas_Eventos.FirstOrDefault(n => n.IdPessoa == Model.Id && n.IdEvento == item.Id);

                            if (Evento != null)
                            {
                                <td style="width:3%">
                                    <p style="color:green">Inscrito</p>
                                </td>
                            }
                            else
                            {

                                <td style="width:3%">
                                    @Html.ActionLink("Inscrever", "RegistraCandidatoAoEvento", "Evento", new { CPF = Model.CPF, Evento = item.Id }, new { @class = "btn btn-primary btn-xs" })
                                </td>
                            }
                                }
                            </tr>
                        }


                    </table>

                </div>





            </div>
        </div>

        @*<div class="form-group">
                <div class="col-md-2">
                    <button type="submit" class="btn btn-primary" style="margin-top: 15px; clear: both">
                        Participar do Evento
                    </button>
                    <img id="ajax-loader" src="~/Images/ajax-loader.gif" style=" display:none; margin-top: 1%" />
                </div>
            </div>*@
    }

}
<div id="result"></div>

BHTecEventos/Views/Evento/Certificado.cshtml
@model List<BHTecEventos.Models.Pessoas_Eventos>
@{
    ViewBag.Title = "Certificado";
    Layout = "~/Views/Shared/_EventoLayout.cshtml";
}
@if (TempData["mensagem"] != null)
{
    <div class="alert alert-success">
        @TempData["mensagem"].ToString()
    </div>
}

<small style="margin-left:2px;color:lightblue gray; font-size:15px">
  Olá Fulano. Os seguintes certificados estão disponíveis para impressão:</small>
<hr />
@if (Model != null)
{
    if (Model.Count != 0)
    {
        <div class="table-responsive">
            <table class="table table-striped" style="background-color:#fff; margin-top:1%">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Data de Realização</th>
                        <th>Palestrante</th>                        
                        <th>Opções</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@Html.DisplayFor(model => item.Eventos.Nome)</td>
                            <td>@Html.DisplayFor(model => item.Eventos.DataAcontecimento)</td>                            
                            <td>@Html.DisplayFor(model => item.Eventos.Organizador)</td>                            
                            <td>
                                @Html.ActionLink("Abrir", "VisualizarPessoa", new { idPes = item.IdPessoa, idSemi = item.IdEvento }, new { @class = "btn btn-default btn-xs" })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    }
    else
    {
        <label>Nenhum Seminário.</label>
    }
}

BHTecEventos/Views/Evento/Index.cshtml
@model BHTecEventos.Models.EventoCPFModel

@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Externo.cshtml";
    //Layout = "~/Views/Shared/_EventoLayout.cshtml";
}

<style>
    #loginadmin {
        padding: 3%;
        width: 35%;
        margin: auto;
        background-color: #f7f7f7;
        -moz-box-shadow: 0 0 6px #a4a4a4;
        -webkit-box-shadow: 0 0 6px #a4a4a4;
        box-shadow: 0 0 6px #a4a4a4;
        border-radius: 8px;
    }

    .Evento_title {
        color: #888888;
        text-align: center;
    }

    .bemvindo_title {
        color: #888888;
        text-align: center;
    }

    body {
        background-image: url(../Images/bg2.png);
    }

    #logo {
        width: 50%;
        height: 50%;
        margin-left: 25%;
        padding-bottom: 2%;
    }

    img {
        max-width: 100%;
        max-height: 100%;
    }

    @@media all and (max-width: 1000px) {
        #logo {
            margin-left: 30%;
        }

        #loginadmin {
            width: 95%;
        }

        h2 {
            font-size: 25px;
        }
    }
</style>


<script>
    jQuery(function ($) {
        $("#CPF").mask("999.999.999-99");
    });
</script>
<div id="loginadmin">
    <div id="logo">
        <img src="~/Images/logo_bhtec.jpg" />
    </div>
    <hr />
    <h5 class="bemvindo_title">BEM VINDO AO SISTEMA INOVA UFMG</h5>
    <hr />
    <h4 class="Evento_title"><strong>EVENTOS PROMOVIDOS PELA INOVA UFMG</strong></h4>
    <hr style="clear: both" />
    @using (Html.BeginForm("BuscaCadastroPessoa", "Evento", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <fieldset>
            <div class="editor-label">
                @Html.LabelFor(model => model.CPF)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(model => model.CPF, new { @class = "form-control", @placeholder = "CPF" })
                @Html.ValidationMessageFor(model => model.CPF, null, new { @style = "color: #f00" })
            </div>

            @Html.ValidationSummary(true, null, new { @style = "color: #f00; margin-top: 2%" })
            <p>
                <input type="submit" value="Continuar" class="btn btn-lg btn-primary btn-block" style="margin-top:5%" />
            </p>
        </fieldset>
    }
</div>