BHTecEventos/Models/Usuarios.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHTecEventos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.Eventos = new HashSet<Eventos>();
            this.PermissaoUsuarios = new HashSet<PermissaoUsuarios>();
        }
    
        public int Codigo { get; set; }
        public string Email { get; set; }
        public string CPF { get; set; }
        public string Nome { get; set; }
        public string Telefone { get; set; }
        public string Senha { get; set; }
        public bool Ativo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Eventos> Eventos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PermissaoUsuarios> PermissaoUsuarios { get; set; }
    }
}

BHTecEventos/Controllers/UsuariosController.cs
using BHTecEventos.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BHTecEventos.AuxCode;
using System.Web.Security;

namespace BHTecEventos.Controllers
{
    public class UsuariosController : Controller
    {
        private EntitiesBHTecEventos db = new EntitiesBHTecEventos();

        [HttpPost]
        public ActionResult Login(EventoCPFModel Candidato)
        {
            if (Request.IsAuthenticated) FormsAuthentication.SignOut();
            return RedirectToAction("BuscaCadastroPessoa","Evento",Candidato);
        }

        public ActionResult ListaUsuarios()
        {
            TempData["mensagem"] = "";
            TempData["atencao"] = "";
            return View(db.Usuarios.ToList());
        }


        public ActionResult CadastrarUsuario()
        {
            TempData["mensagem"] = "";
            TempData["atencao"] = "";
            return View();
        }

        [HttpPost]
        public ActionResult CadastrarUsuario(Usuarios U)
        {
            TempData["mensagem"] = "";
            TempData["atencao"] = "";
            if (ModelState.IsValid)
            {
                try
                {
                    U.Senha = Sec.Encrypt(U.Senha);
                    db.Usuarios.Add(U);
                    db.SaveChanges();
                    TempData["mensagem"] = "Usuário Cadastrado com sucesso.";
                }
                catch (DbEntityValidationException e)
                {
                    foreach (var eve in e.EntityValidationErrors)
                    {
                        //Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:", eve.Entry.Entity.GetType().Name, eve.Entry.State);
                        //Erro += "Entity of type \"{0}\" in state \"{1}\" has the following validation errors:" + eve.Entry.Entity.GetType().Name + eve.Entry.State;
                        foreach (var ve in eve.ValidationErrors)
                        {
                            //Console.WriteLine("- Property: \"{0}\", Error: \"{1}\"",ve.PropertyName, ve.ErrorMessage);
                            //Erro += "- Property: \"{0}\", Error: \"{1}\"" + ve.PropertyName + ve.ErrorMessage;
                            TempData["atencao"] += ve.ErrorMessage + "\n";
                        }
                    }

                }
            }
            return View(U);
        }

        public ActionResult AtualizarUsuario(int id)
        {
            TempData["mensagem"] = "";
            TempData["atencao"] = "";
            return View(db.Usuarios.Find(id));
        }

        [HttpPost]
        public ActionResult AtualizarUsuario(Usuarios U)
        {
            TempData["mensagem"] = "";
            TempData["atencao"] = "";
            if (ModelState.IsValid)
            {

                try
                {
                    Usuarios LU = db.Usuarios.Find(U.Codigo);
                    LU.Nome = U.Nome;
                    LU.Email = U.Email;
                    LU.CPF = U.CPF;
                    LU.Telefone = U.Telefone;
                    LU.Ativo = U.Ativo;
                    LU.Senha = Sec.Encrypt(U.Senha); ;
                    db.Entry(LU).State = EntityState.Modified;
                    db.SaveChanges();
                    TempData["mensagem"] = "Usuário Cadastrado com sucesso.";
                }
                catch (DbEntityValidationException e)
                {
                    foreach (var eve in e.EntityValidationErrors)
                    {
                        //Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:", eve.Entry.Entity.GetType().Name, eve.Entry.State);
                        //Erro += "Entity of type \"{0}\" in state \"{1}\" has the following validation errors:" + eve.Entry.Entity.GetType().Name + eve.Entry.State;
                        foreach (var ve in eve.ValidationErrors)
                        {
                            //Console.WriteLine("- Property: \"{0}\", Error: \"{1}\"",ve.PropertyName, ve.ErrorMessage);
                            //Erro += "- Property: \"{0}\", Error: \"{1}\"" + ve.PropertyName + ve.ErrorMessage;
                            TempData["atencao"] += ve.ErrorMessage + "\n";
                        }
                    }

                }
            }
            return View(U);
        }

        public ActionResult ExcluirUsuario(int id)
        {
            TempData["mensagem"] = "";
            TempData["atencao"] = "";
            Usuarios U = db.Usuarios.Find(id);
            if (U.Nome == "Administrador")
            {
                TempData["atencao"] = "Este usário não pode ser Excluído";
            }
            else
            {
                db.Usuarios.Remove(U);
                db.SaveChanges();
            }
            return View("ListaUsuarios", db.Usuarios.ToList());
        }


    }
}

BHTecEventos/Views/Usuarios/AtualizarUsuario.cshtml
@model BHTecEventos.Models.Usuarios

@{
    ViewBag.Title = "AtualizarUsuario";
    Layout = "~/Views/Shared/_EventoLayout.cshtml";
}
<script>

    jQuery(function ($) {
        $("#CPF").mask("999.999.999-99");
        $('#Telefone').mask("(99) 9999-9999?9");
        $('#Telefone').change(function (event) {
            var target, phone, element;
            target = (event.currentTarget) ? event.currentTarget : event.srcElement;
            phone = target.value.replace(/\D/g, '');
            element = $(target); element.unmask();
            if (phone.length > 10) {
                element.mask("(99) 99999-999?9");
            }
            else {
                element.mask("(99) 9999-9999?9");
            }
        });

    });
</script>

<h2>Atualizar Usuário</h2>
@if (!String.IsNullOrEmpty(TempData["mensagem"].ToString()))
{
    <div class="alert alert-info">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        @TempData["mensagem"]
    </div>
}

@if (!String.IsNullOrEmpty(TempData["atencao"].ToString()))
{
    <div class="alert alert-warning">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        @TempData["atencao"]
    </div>
}
<hr />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div class="form-group">
        <div class="col-lg-8">
            @Html.HiddenFor(model => model.Codigo)
            @Html.LabelFor(model => model.Nome)
            @if (Model.Nome == "Administrador")
            {
                @Html.TextBoxFor(model => model.Nome, new { @class = "form-control pt1", @placeholder = "Nome", @required = true, @readonly="true"} );
            }
            else
            {
                @Html.TextBoxFor(model => model.Nome, new { @class = "form-control pt1", @placeholder = "Nome", @required = true })
            }
            @Html.ValidationMessageFor(model => model.Nome)
        </div>
    </div>


    <div class="form-group">
        <div class="col-lg-8">
            @Html.LabelFor(model => model.Email)
            @Html.TextBoxFor(model => model.Email, new { @class = "form-control pt1", @placeholder = "email", @required = true })
            @Html.ValidationMessageFor(model => model.Email)
        </div>
    </div>

    <div class="form-group">
        <div class="col-lg-8">
            @Html.LabelFor(model => model.CPF)
            @Html.TextBoxFor(model => model.CPF, new { @class = "form-control pt1", @placeholder = "CPF", @required = true })
            @Html.ValidationMessageFor(model => model.CPF)
        </div>
    </div>



    <div class="form-group">
        <div class="col-lg-8">
            @Html.LabelFor(model => model.Telefone)
            @Html.TextBoxFor(model => model.Telefone, new { @class = "form-control pt1", @placeholder = "Telefone", @required = true })
            @Html.ValidationMessageFor(model => model.Telefone)
        </div>
    </div>

    <div class="form-group">
        <div class="col-lg-8">
            @Html.LabelFor(model => model.Senha)
            @Html.PasswordFor(model => model.Senha, new { @class = "form-control pt1", @placeholder = "Senha", @required = true })
            @Html.ValidationMessageFor(model => model.Senha)
        </div>
    </div>

    <div class="form-group">
        <div class="col-lg-8">
            @Html.LabelFor(model => model.Ativo)
            @Html.EditorFor(model => model.Ativo)
            @Html.ValidationMessageFor(model => model.Ativo)
        </div>
    </div>
    <p>
        <input type="submit" value="Atualizar" class="btn btn-primary" />
        @Html.ActionLink("Voltar", "ListaUsuarios", "Usuarios", null, new { @class = "btn btn-default" })
    </p>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BHTecEventos/Views/Usuarios/CadastrarUsuario.cshtml
@model BHTecEventos.Models.Usuarios

@{
    ViewBag.Title = "CadastrarUsuario";
    Layout = "~/Views/Shared/_EventoLayout.cshtml";
}

<script>

    jQuery(function ($) {
        $("#CPF").mask("999.999.999-99");
        $('#Telefone').mask("(99) 9999-9999?9");
        $('#Telefone').change(function (event) {
            var target, phone, element;
            target = (event.currentTarget) ? event.currentTarget : event.srcElement;
            phone = target.value.replace(/\D/g, '');
            element = $(target); element.unmask();
            if (phone.length > 10) {
                element.mask("(99) 99999-999?9");
            }
            else {
                element.mask("(99) 9999-9999?9");
            }
        });       

    });
</script>
<h2>Cadastrar Usuário</h2>
@if (!String.IsNullOrEmpty(TempData["mensagem"].ToString()))
{
    <div class="alert alert-info">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        @TempData["mensagem"]
    </div>
}

@if (!String.IsNullOrEmpty(TempData["atencao"].ToString()))
{
    <div class="alert alert-warning">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        @TempData["atencao"]
    </div>
}
<hr />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div class="form-group">
        <div class="col-lg-8">
            @Html.LabelFor(model => model.Nome)
            @Html.TextBoxFor(model => model.Nome, new { @class = "form-control pt1", @placeholder = "Nome", @required = true })
            @Html.ValidationMessageFor(model => model.Nome)
        </div>
    </div>


    <div class="form-group">
        <div class="col-lg-8">
            @Html.LabelFor(model => model.Email)
            @Html.TextBoxFor(model => model.Email, new { @class = "form-control pt1", @placeholder = "email", @required = true })
            @Html.ValidationMessageFor(model => model.Email)
        </div>
    </div>

    <div class="form-group">
        <div class="col-lg-8">
            @Html.LabelFor(model => model.CPF)
            @Html.TextBoxFor(model => model.CPF, new { @class = "form-control pt1", @placeholder = "CPF", @required = true })
            @Html.ValidationMessageFor(model => model.CPF)
        </div>
    </div>

   

    <div class="form-group">
        <div class="col-lg-8">
            @Html.LabelFor(model => model.Telefone)
            @Html.TextBoxFor(model => model.Telefone, new { @class = "form-control pt1", @placeholder = "Telefone", @required = true })
            @Html.ValidationMessageFor(model => model.Telefone)
        </div>
    </div>

    <div class="form-group">
        <div class="col-lg-8">
            @Html.LabelFor(model => model.Senha)
            @Html.PasswordFor(model => model.Senha, new { @class = "form-control pt1", @placeholder = "Senha", @required = true })
            @Html.ValidationMessageFor(model => model.Senha)
        </div>
    </div>

    <div class="form-group">
        <div class="col-lg-8">
            @Html.LabelFor(model => model.Ativo)
            @Html.EditorFor(model => model.Ativo)
            @Html.ValidationMessageFor(model => model.Ativo)
        </div>
    </div>
    <p>
        <input type="submit" value="Cadastrar" class="btn btn-primary" />
        @Html.ActionLink("Voltar", "ListaUsuarios", "Usuarios",null, new { @class = "btn btn-default" })
    </p>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BHTecEventos/Views/Usuarios/ListaUsuarios.cshtml
@model IEnumerable<BHTecEventos.Models.Usuarios>

@{
    ViewBag.Title = "ListaUsuarios";
    Layout = "~/Views/Shared/_EventoLayout.cshtml";
}

<h2>Usuários do Sistema</h2>
@if (TempData["mensagem"] != "")
{
    <div class="alert alert-info">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        @TempData["mensagem"]
    </div>
}

@if (TempData["atencao"] != "")
{
    <div class="alert alert-warning">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        @TempData["atencao"]
    </div>
}


<p>
    @Html.ActionLink("Cadastrar Novo Usuário", "CadastrarUsuario","Usuario",null)
</p>
<div class="table-responsive">
    <table class="table table-striped" style="background-color:#fff; margin-top:1%">
        <thead>
            <tr>
                @*<th>
                    @Html.DisplayNameFor(model => model.Codigo)
                </th>*@
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CPF)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Nome)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Telefone)
                </th>
                
                <th>
                    @Html.DisplayNameFor(model => model.Ativo)
                </th>
                <th>@Html.Label("Opções")</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    @*<td>
                        @Html.DisplayFor(modelItem => item.Codigo)
                    </td>*@
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CPF)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Telefone)
                    </td>
                   
                    <td>
                        @Html.DisplayFor(modelItem => item.Ativo)
                    </td>
                    <td>
                        @Html.ActionLink("Atualizar", "AtualizarUsuario", new {  id=item.Codigo}) |
                        @Html.ActionLink("Excluir", "ExcluirUsuario", new { id = item.Codigo })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

</table>